### PR TITLE
Add standard CSS `transform` property

### PR DESCRIPTION
**Pull request by iamdustan**
I didn’t listen to your README warning.

This looks awesome.

### CODE REVIEW

**Comment by chenglou** [comment]
omg lol, fine!

`transform` seems to work in all modern browsers now? I guess you can just remove `Webkit` prefix altogether

**Comment by iamdustan** [comment]
:)

iOS 8/Safari 8 still require the `-webkit-` prefix, laggards.

**Comment by chenglou** [comment]
Merging then!
Feel free to create new issues and ask questions (I welcome those, in case I'm missing something), but keep this low profile please!

**Comment by iamdustan** [comment]
Will do. I need to play more. We all have our lo-pro projects :)

**Pull request merged**
